
# Week 1: Introduction to Artificial Neural Networks (ANNs)
## Objective:
In this notebook, we will explore the basics of artificial neural networks (ANNs) and learn about key concepts like vectors, matrices, tensors, weights, and biases. By the end of this notebook, you will be able to implement a basic single-layer perceptron using Python and NumPy.



## 1.1 Theory: What are Artificial Neural Networks (ANNs)?
An artificial neural network is inspired by the biological neural networks in the human brain. It consists of neurons (nodes), weights, and biases. The basic idea of an ANN is to take input data, perform computations using weights and biases, and output the results. ANNs are primarily used for tasks such as classification, regression, and pattern recognition.

### Key Concepts:
- **Vectors**: A collection of numbers arranged in a specific order.
- **Matrices**: A 2D array of numbers, used for representing input data or weights in a neural network.
- **Tensors**: A generalization of vectors and matrices to higher dimensions.
- **Weights**: Parameters that control the importance of input features.
- **Biases**: Values added to the input to shift the activation function.


In [1]:

import numpy as np

# Vector example
vector = np.array([1, 2, 3])
print("Vector:", vector)


Vector: [1 2 3]


In [2]:

# Matrix example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)


Matrix:
 [[1 2 3]
 [4 5 6]]


In [3]:

# Tensor example
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)


Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]



## 1.2 Coding: Implementing a Simple ANN

Let's implement a basic **single-layer perceptron** using Python and NumPy. The perceptron is the simplest type of neural network and is used for binary classification tasks.

The perceptron computes the weighted sum of the inputs and applies an activation function (like step function or sigmoid) to decide the output.

### Perceptron Model:

$$ y = f(\sum(w_i x_i) + b) $$

Where:
- \( w_i \) are the weights,
- \( x_i \) are the input features,
- \( b \) is the bias,
- \( f \) is the activation function (e.g., step function or sigmoid).


In [4]:

# Perceptron implementation using step function as activation

def step_function(x):
    return 1 if x >= 0 else 0

class Perceptron:
    def __init__(self, input_size, lr=0.1):
        self.weights = np.zeros(input_size)
        self.bias = 0
        self.lr = lr

    def predict(self, inputs):
        linear_output = np.dot(inputs, self.weights) + self.bias
        return step_function(linear_output)

    def train(self, X, y, epochs=10):
        for _ in range(epochs):
            for inputs, label in zip(X, y):
                prediction = self.predict(inputs)
                self.weights += self.lr * (label - prediction) * inputs
                self.bias += self.lr * (label - prediction)

# XOR data for training
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])  # AND gate

# Training perceptron
perceptron = Perceptron(input_size=2)
perceptron.train(X, y)

# Testing perceptron
for inputs in X:
    print(f"Input: {inputs}, Predicted Output: {perceptron.predict(inputs)}")


Input: [0 0], Predicted Output: 0
Input: [0 1], Predicted Output: 0
Input: [1 0], Predicted Output: 0
Input: [1 1], Predicted Output: 1



## 1.3 Exercises:
- Modify the perceptron code to implement an OR gate instead of an AND gate.
- Use a different activation function, such as the sigmoid function, and observe the difference in output.
- Train the perceptron on a dataset with more than two inputs.
